apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postfix.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "postfix.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "postfix.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "postfix.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: postfix
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "/etc/postfix/entrypoint.sh"]
          env:
            - name: SMTP_SERVER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.smtp.secretName }}
                  key: smtp-server
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.smtp.secretName }}
                  key: smtp-user
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.smtp.secretName }}
                  key: smtp-password
          ports:
            - containerPort: 25
          volumeMounts:
            - name: postfix-config
              mountPath: /etc/postfix/main.cf.template
              subPath: main.cf.template
            - name: postfix-config
              mountPath: /etc/postfix/entrypoint.sh
              subPath: entrypoint.sh
      volumes:
        - name: postfix-config
          configMap:
            name: {{ include "postfix.fullname" . }}-config

