apiVersion: v1
kind: Service
metadata:
  name: {{ include "postfix.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "postfix.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 25
      protocol: TCP
      name: smtp
  selector:
    app.kubernetes.io/name: {{ include "postfix.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
