# image:
#   repository: bitnami/fluentd
#   tag: 1.16.3-debian-11-r1
#   pullPolicy: IfNotPresent

# extraPlugins: "fluent-plugin-s3"

# env:
#   - name: AWS_ACCESS_KEY_ID
#     valueFrom:
#       secretKeyRef:
#         name: fluentd-s3-credentials
#         key: AWS_ACCESS_KEY_ID
#   - name: AWS_SECRET_ACCESS_KEY
#     valueFrom:
#       secretKeyRef:
#         name: fluentd-s3-credentials
#         key: AWS_SECRET_ACCESS_KEY

# command:
#   - /opt/bitnami/fluentd/bin/fluentd
#   - -c
#   - /opt/bitnami/fluentd/conf/fluentd.conf
#   - -p
#   - /opt/bitnami/fluentd/plugins
#   - --gemfile
#   - /opt/bitnami/fluentd/Gemfile

# livenessProbe:
#   enabled: false
# readinessProbe:
#   enabled: false

# persistence:
#   enabled: false

# volumeMounts:
#   - name: varlog
#     mountPath: /var/log

# volumes:
#   - name: varlog
#     hostPath:
#       path: /var/log
# configMap:
#   create: true
#   name: fluentd-config
#   content: |
#     <source>
#       @type tail
#       path /var/log/containers/*.log
#       pos_file /var/log/fluentd-containers.log.pos
#       tag kube.*
#       format json
#     </source>

#     <match **>
#       @type s3
#       aws_key_id YOUR_KEY
#       aws_sec_key YOUR_SECRET
#       s3_bucket fugue-state-backend
#       s3_region nyc3
#       s3_endpoint https://nyc3.digitaloceanspaces.com
#       path logs/
#       store_as gzip
#       force_path_style true
#       use_ssl true
#     </match>
fullnameOverride: fluentd

rbac:
  create: true

serviceAccount:
  create: true
  name: fluentd

input:
  tail:
    enabled: true
    path: /var/log/containers/*.log
    pos_file: /opt/bitnami/fluentd/logs/buffer/containers.pos
    tag: kube.*
    parser: cri

parsers:
  enabled: true
  config: |
    <parse>
      @type cri
    </parse>

output:
  custom: |
    <match **>
      @type s3

      aws_key_id "#{ENV['DO_SPACES_KEY']}"
      aws_sec_key "#{ENV['DO_SPACES_SECRET']}"
      s3_bucket fugue-state-backend
      s3_region nyc3
      s3_endpoint https://nyc3.digitaloceanspaces.com
      path logs/
      store_as json

      force_path_style true
      time_slice_format %Y/%m/%d/%H
      time_slice_wait 10m
      buffer_path /opt/bitnami/fluentd/logs/buffer/s3
      buffer_chunk_limit 5M
      buffer_queue_limit 32
      flush_interval 10s
      retry_wait 30s
      max_retry_wait 300
      disable_retry_limit false
      num_threads 2
    </match>

env:
  - name: DO_SPACES_KEY
    valueFrom:
      secretKeyRef:
        name: fluentd-s3-credentialss
        key: accessKey
  - name: DO_SPACES_SECRET
    valueFrom:
      secretKeyRef:
        name: fluentd-s3-credentials
        key: secretKey

volumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: buffer
    mountPath: /opt/bitnami/fluentd/logs/buffer

volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: buffer
    emptyDir: {}
