apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jumpbox-dns
  namespace: jump
spec:
  secretName: jumpbox-dns-dummy-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - jump.fugue-state.io
