apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: events-sensor
  namespace: processing
spec:
  dependencies:
    - name: event-dependency
      eventSourceName: event-source-name
      eventName: event-name
  triggers:
    - template:
        name: trigger-name
        k8s:
          operation: create
          source:
            resource:
              apiVersion: v1
              kind: Pod
              metadata:
                generateName: triggered-pod-
                namespace: default
              spec:
                containers:
                  - name: busybox
                    image: busybox
                    command: ["sh", "-c", "echo Event Triggered! && sleep 3600"]
                    env:
                      - name: AWS_ACCESS_KEY_ID
                        valueFrom:
                          secretKeyRef:
                            name: s3-access-secret
                            key: accessKey
                      - name: AWS_SECRET_ACCESS_KEY
                        valueFrom:
                          secretKeyRef:
                            name: s3-access-secret
                            key: secretKey
          parameters:
            - src:
                dependencyName: event-dependency
                dataKey: body.object.key
              dest: spec.containers[0].env[2].value
            - src:
                dependencyName: event-dependency
                dataKey: body.bucket.name
              dest: spec.containers[0].env[3].value