apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fugue-state-ui.fullname" . }}
  labels:
    {{- include "fugue-state-ui.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fugue-state-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        reloader.stakater.com/match: "true"
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fugue-state-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fugue-state-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- range .Values.initContainers }}
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          command: ["sh", "-c", " /application/scripts/build.sh && cp -r /application/* /application-volume/"]
          volumeMounts:
            - name: application-volume
              mountPath: /application-volume
            {{- toYaml .volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          envFrom:
          - secretRef:
              name: fugue-state-ui-secrets
        {{- end }}
      volumes:
        - name: application-volume
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          volumeMounts:
          - name: application-volume
            mountPath: /application
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 300
            timeoutSeconds: 1800
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 300
            timeoutSeconds: 1800
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
          - secretRef:
              name: fugue-state-ui-secrets
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
