name: postfix
description: A Helm chart for Postfix
version: 0.1.0
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Postfix_logo.svg/1200px-Postfix_logo.svg.png
type: application
keywords:
  - postfix
  - smtp
  - mail
sources:
  - https://github.com/boky/postfix
maintainers:
  - name: Boky
    email: boky@gmail.com
    url: https://github.com/boky
