replicaCount: 1

config:
  postfix:
    myhostname: fugue-state.io

image:
  repository: registry.digitalocean.com/fugue-state-registry/postfix
  tag: v0.0.7
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 25

resources:
  limits:
    cpu: 50m
    memory: 100Mi
  requests:
    cpu: 10m
    memory: 50Mi

smtp:
  # These are injected from the Kubernetes Secret (postfix-secrets)
  secretName: postfix-secrets

nodeSelector: {}
tolerations: []
affinity: {}
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
