kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operate-workflow-sa-binding
  namespace: scan
subjects:
  - kind: ServiceAccount
    name: operate-workflow-sa
    namespace: scan
roleRef:
  kind: ClusterRole
  name: operate-workflow-role
  apiGroup: rbac.authorization.k8s.io