apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: ghcn-daily-stations
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: "Allow"
  startingDeadlineSeconds: 0
  workflowSpec:
    serviceAccountName: operate-workflow-sa
    entrypoint: main
    templates:
    - name: main
      dag:
        tasks:
          - name: curl-ghcnd-stations
            templateRef:
              name: curl-ghcnd-stations-template
              template: curl-ghcnd-stations

