apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: ghcn-daily-stations
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: "Allow"
  startingDeadlineSeconds: 0
  workflowSpec:
    imagePullSecrets:
      - name: fugue-state-registry
    serviceAccountName: operate-workflow-sa
    entrypoint: main
    templates:
    - name: main
      dag:
        tasks:
          - name: curl-stations
            templateRef:
              name: curl-ghcnd-stations-template
              template: curl-ghcnd-stations

          - name: stations-json
            depends: curl-stations
            templateRef:
              name: curl-ghcnd-stations-template
              template: stations-json-list
            arguments:
              artifacts:
              - name: ghcnd-stations-csv
                from: "{{`{{tasks.curl-stations.outputs.artifacts.ghcnd-stations}}`}}"

          - name: curl-values
            depends: stations-json
            templateRef:
              name: curl-ghcnd-stations-template
              template: curl-ghcnd-values
            arguments:
              parameters:
              - name: station
                value: "{{`{{item.station}}`}}"
            withParam: "{{`{{tasks.stations-json.outputs.parameters.ghcnd-stations}}`}}"
