apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: ghcn-daily-stations
spec:
  serviceAccountName: operate-workflow-sa
  schedule: "0 0 * * *"
  workflowSpec:
    entrypoint: curl-ghcnd-stations
    templates:
    - name: curl-ghcnd-stations
      templateRef:
        name: curl-ghcnd-stations
        template: curl-ghcnd-stations-template
