apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: ghcn-daily-stations
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: "Allow"
  startingDeadlineSeconds: 0
  workflowSpec:
    imagePullSecrets:
      - name: fugue-state-registry
    serviceAccountName: operate-workflow-sa
    entrypoint: main
    templates:
    - name: main
      dag:
        tasks:
          - name: curl-stations
            workflowTemplateRef:
              name: curl-ghcnd-stations-template
              template: curl-ghcnd-stations

          - name: stations-json
            depends: curl-stations
            workflowTemplateRef:
              name: curl-ghcnd-stations-template
              template: stations-json-list
            arguments:
              artifacts:
              - name: ghcnd-stations-csv
                from: "{{`{{tasks.curl-stations.outputs.artifacts.ghcnd-stations}}`}}"

          - name: slice-stations-json
            depends: stations-json
            workflowTemplateRef:
              name: curl-ghcnd-stations-template
              template: slice-stations-json
            arguments:
              parameters:
              - name: slice_index
                value: "{{`{{item}}`}}"
              - name: number_of_slices
                value: 40
              artifacts:
              - name: ghcnd-stations-json
                from: "{{`{{tasks.stations-json.outputs.artifacts.ghcnd-stations}}`}}"
            withParam: '[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]'
    volumes:
    - name: out
      emptyDir: { }