kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-sa-binding
  namespace: ci
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ci
roleRef:
  kind: ClusterRole
  name: operate-workflow-role
  apiGroup: rbac.authorization.k8s.io