apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github-dep
      eventSourceName: github
      eventName: repo_hook
  triggers:
    - template:
        name: github-sensor-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-
              spec:
                serviceAccountName: operate-workflow-sa
                arguments:
                  parameters:
                    - name: body
                entrypoint: main
                templates:
                  - name: main
                    dag:
                      tasks:
                        - name: body-to-artifact
                          template: body-to-artifact
                        
                        - name: cat-artifact
                          depends: body-to-artifact
                          template: cat-artifact
                          arguments:
                            artifacts:
                              - name: body
                                from: "{{`{{tasks.body-to-artifact.outputs.artifacts.body}}`}}"

                        - name: get-event
                          depends: body-to-artifact
                          template: get-event
                          arguments:
                            artifacts:
                              - name: body
                                from: "{{`{{tasks.body-to-artifact.outputs.artifacts.body}}`}}"

                        - name: push-event
                          when: "{{`{{tasks.get-event.outputs.result}}`}} == push"
                          template: push-event
                        
                  - name: body-to-artifact
                    inputs:
                      parameters:
                        - name: body
                          value: '{{`{{workflow.parameters.body}}`}}'
                    script:
                      image: alpine
                      command: [sh]
                      source: |
                        set -e
                        cat <<EOF > /body.json
                        {{`{{inputs.parameters.body}}`}}
                        EOF
                    outputs:
                      artifacts:
                        - name: body
                          path: "/body.json"

                  - name: cat-artifact
                    inputs:
                      artifacts:
                        - name: body
                          path: "/body.json"
                    script:
                      image: alpine
                      command: [sh]
                      source: |
                        set -e
                        cat /body.json

                  - name: get-event
                    inputs:
                      artifacts:
                        - name: body
                          path: "/body.json"
                    script:
                      image: badouralix/curl-jq
                      command: [sh]
                      source: |
                        set -e
                        cat /body.json | jq -r '.["X-GitHub-Event"]'

                  - name: push-event
                    script:
                      image: badouralix/curl-jq
                      command: [sh]
                      source: |
                        set -e
                        echo "push-event"
          parameters:
            - src:
                dependencyName: github-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value