apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github-dep
      eventSourceName: github
      eventName: repo_hook
  triggers:
    - template:
        name: github-sensor-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              serviceAccountName: operate-workflow-sa
              metadata:
                generateName: github-
              spec:
                arguments:
                  parameters:
                    - name: body
                entrypoint: argosay
                templates:
                  - name: argosay
                    inputs:
                      parameters:
                        - name: body
                          value: '{{workflow.parameters.body}}'
                    container:
                      name: main
                      image: argoproj/argosay:v2
                      command:
                        - /argosay
                      args:
                        - echo
                        - '{{inputs.parameters.body}}'
          parameters:
            - src:
                dependencyName: github-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value