apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github-dep
      eventSourceName: github
      eventName: repo_hook
  triggers:
    - template:
        name: github-sensor-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              serviceAccountName: operate-workflow-sa
              metadata:
                generateName: github-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                    - name: body
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: body
                    container:
                      image: curlimages/curl:8.2.1
                      command: [sh]
                      source: >
                        echo "Hello argo"
          parameters:
            - src:
                dependencyName: github-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value