apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github-dep
      eventSourceName: github
      eventName: repo_hook
  triggers:
    - template:
        name: github-sensor-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-
              spec:
                volumes:
                - name: docker-config
                  secret:
                    secretName: docker-config
                serviceAccountName: operate-workflow-sa
                arguments:
                  parameters:
                    - name: body
                entrypoint: main
                imagePullSecrets:
                - name: fugue-state-registry
                templates:
                  - name: main
                    dag:
                      tasks:
                        - name: body-to-artifact
                          template: body-to-artifact

                        - name: get-workflow-parameters
                          depends: body-to-artifact
                          template: get-workflow-parameters
                          arguments:
                            artifacts:
                              - name: body
                                from: "{{`{{tasks.body-to-artifact.outputs.artifacts.body}}`}}"

                        - name: push-event
                          depends: get-workflow-parameters && body-to-artifact
                          when: "{{`{{tasks.get-workflow-parameters.outputs.parameters.event}}`}} == 'push'"
                          template: push-event
                          arguments:
                            artifacts:
                              - name: argo-source
                                path: /src
                                git:
                                  repo: "{{`{{tasks.get-workflow-parameters.outputs.parameters.repo}}`}}"
                                  revision: "{{`{{tasks.get-workflow-parameters.outputs.parameters.parameters}}`}}"
                              - name: body
                                from: "{{`{{tasks.body-to-artifact.outputs.artifacts.body}}`}}"

                        - name: image
                          depends: get-workflow-parameters && body-to-artifact && push-event
                          template: image
                          arguments:
                            artifacts:
                              - name: argo-source
                                path: /src
                                git:
                                  repo: "{{`{{tasks.get-repo.outputs.result}}`}}"
                                  revision: "{{`{{tasks.get-revision.outputs.result}}`}}"
                              - name: body
                                from: "{{`{{tasks.body-to-artifact.outputs.artifacts.body}}`}}"
                            parameters:
                              - name: image
                                value: "registry.digitalocean.com/fugue-state-registry/{{`{{item.image}}`}}:{{`{{tasks.push-event.outputs.parameters.tag}}`}}"
                              - name: dockerfile
                                value: "{{`{{item.dockerfile}}`}}"
                          withParam: "{{`{{tasks.push-event.outputs.parameters.ci}}`}}"

                        - name: check-suite-event
                          depends: get-workflow-parameters && body-to-artifact
                          when: "{{`{{tasks.get-workflow-parameters.outputs.parameters.event}}`}} == 'check_suite'"
                          template: check-suite-event
                          arguments:
                            artifacts:
                              - name: argo-source
                                path: /src
                                git:
                                  repo: "{{`{{tasks.get-repo.outputs.result}}`}}"
                                  revision: "{{`{{tasks.get-revision.outputs.result}}`}}"
                              - name: body
                                from: "{{`{{tasks.body-to-artifact.outputs.artifacts.body}}`}}"
                        
                  - name: body-to-artifact
                    script:
                      image: alpine
                      command: [sh]
                      source: |
                        set -e
                        cat <<EOF > /body.json
                        {{`{{workflow.parameters.body}}`}}
                        EOF
                    outputs:
                      artifacts:
                        - name: body
                          path: "/body.json"

                  - name: get-workflow-parameters
                    inputs:
                      artifacts:
                        - name: body
                          path: "/body.json"
                    script:
                      image: registry.digitalocean.com/fugue-state-registry/workflow-task-image:2c38fe6c
                      command: [sh]
                      source: |
                        set -e
                        cat /body.json | jq -r '.["repository"] | .["clone_url"]' > /repo.txt
                        cat /body.json | jq -r '.["X-GitHub-Event"]' > /event.txt
                        cat /body.json | jq -r '.["after"] | select( . != null )' >> /revision.txt
                        cat /body.json | jq -r '.["check_suite"] | .["after"] | select( . != null )' >> /revision.txt
                    outputs:
                      parameters:
                        - name: repo
                          valueFrom:
                            path: /repo.txt
                        - name: event
                          valueFrom:
                            path: /event.txt
                        - name: revision
                          valueFrom:
                            path: /revision.txt

                  - name: push-event
                    inputs:
                      artifacts:
                      - name: argo-source
                        path: /src
                      - name: body
                        path: "/body.json"
                    script:
                      image: registry.digitalocean.com/fugue-state-registry/workflow-task-image:2c38fe6c
                      command: [bash]
                      source: |
                        set -e
                        cd /src
                        export GIT_REF=$(cat /body.json | jq -r '.["ref"]')
                        export MASTER_BRANCH=$(cat /body.json | jq -r '.["repository"] | .["master_branch"]')

                        export TAG=$(git rev-parse HEAD)
                        echo ${TAG:0:8} > /tag.txt

                        if [[ $GIT_REF == *$MASTER_BRANCH ]] # * is used for pattern matching
                        then
                          if [ -f "/src/ci.json" ]; then
                            cat /src/ci.json > ci.json
                          else
                            echo "[]" > /ci.json
                          fi
                        else
                          exit 1
                        fi
                    outputs:
                      parameters:
                        - name: ci
                          valueFrom:
                            path: /ci.json
                        - name: tag
                          valueFrom:
                            path: /tag.txt

                  - name: check-suite-event
                    inputs:
                      artifacts:
                      - name: argo-source
                        path: /src
                      - name: body
                        path: "/body.json"
                    script:
                      image: registry.digitalocean.com/fugue-state-registry/workflow-task-image:2c38fe6c
                      command: [sh]
                      source: |
                        set -e
                        if [ -f "/src/check_suite.sh" ]; then
                          bash /src/check_suite.sh
                        fi

                  - name: image
                    inputs:
                      parameters:
                        - name: image
                    volumes:
                      - name: docker-config
                        secret:
                          secretName: docker-config
                    container:
                      readinessProbe:
                        exec:
                          command: [ sh, -c, "buildctl debug workers" ]
                      image: moby/buildkit:v0.9.3-rootless
                      volumeMounts:
                        - name: docker-config
                          mountPath: /.docker
                      workingDir: /src/
                      env:
                        - name: BUILDKITD_FLAGS
                          value: --oci-worker-no-process-sandbox
                        - name: DOCKER_CONFIG
                          value: /.docker
                      command:
                        - buildctl-daemonless.sh
                      args:
                        - build
                        - --frontend
                        - dockerfile.v0
                        - --local
                        - context=.
                        - --local
                        - dockerfile=.
                        - --output
                        - type=image,name=docker.io/{{`{{inputs.parameters.image}}`}},push=true
          parameters:
            - src:
                dependencyName: github-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value