apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-sensor
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github-sensor-dependencies
      eventSourceName: github
      eventName: github-event
      filters:
        data:
          - path: body.pull_request.base.ref
            type: string
            value:
              - develop
  triggers:
    - template:
        name: github-workflow-trigger
        k8s:
          operation: create
          parameters:
            - src:
                dependencyName: github-sensor-dependencies
                dataKey: body.repository.name
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: github-trunk-dependencies
                dataTemplate: "{{`{{ .Input.body.repository.head.sha }}`}}"
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: github-trunk-dependencies
                dataTemplate: "{{`{{ .Input.body.pull_request.head.sha | substr 0 7 }}`}}"
              dest: spec.arguments.parameters.2.value
            # Append pull request number and short sha to dynamically assign workflow name <github-21500-2c065a>
            - src:
                dependencyName: github-trunk-dependencies
                dataTemplate: "{{`{{ .Input.body.repository.name }}-{{ .Input.body.pull_request.head.sha | substr 0 7 }}`}}"
              dest: metadata.generateName
              operation: append
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                namespace: ci
                generateName: github-
              spec:
                entrypoint: main
                arguments:
                  parameters:
                    - name: repository
                    - name: sha
                    - name: short-sha
                templates:
                  - name: main
                    inputs:
                      parameters:
                        - name: repository
                        - name: sha
                        - name: short-sha
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["{{`{{inputs.parameters.repository}}-{{inputs.parameters.sha}}`}}"]