apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: push-develop
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github-dep
      eventSourceName: github
      eventName: push-develop
      filters:
        data:
          # Type of Github event that triggered the delivery: [pull_request, push, issues, label, ...]
          # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads
          - path: body.X-GitHub-Event
            type: string
            value:
              - push
          - path: body.ref
            type: string
            value:
              - refs/heads/develop
  triggers:
    - template:
        name: github-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: push-develop-
              spec:
                entrypoint: main
                arguments:
                  parameters:
                    - name: body
                templates:
                  - name: main
                    dag:
                      tasks:
                        - name: body-to-artifact
                          outputs:
                            artifacts:
                              - name: body
                                path: "/body.json"
                          script:
                            image: alpine
                            command: [sh]
                            source: |
                              set -e
                              cat <<EOF > /body.json
                              {{workflow.parameters.body}}
                              EOF
                        - name: cat-artifact
                          inputs:
                            artifacts:
                            - name: body
                            path: "/body.json"
                          script:
                            image: alpine
                            command: [sh]
                            source: |
                              set -e
                              cat /body.json
          parameters:
            - src:
                dependencyName: github-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value