apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: push-develop
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github-dep
      eventSourceName: github
      eventName: push-develop
      filters:
        data:
          # Type of Github event that triggered the delivery: [pull_request, push, issues, label, ...]
          # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads
          - path: headers.X-Github-Event
            type: string
            value:
              - push
          - path: body.pull_request.base.ref
            type: string
            value:
              - develop
  triggers:
    - template:
        name: github-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: push-develop-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                    - name: body
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: body
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["{{`{{inputs.parameters.body}}`}}"]
          parameters:
            - src:
                dependencyName: github-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value