apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: curl-ghcnd-template
spec:
  serviceAccountName: operate-workflow-sa
  templates:
    - name: whalesay-template
      container:
        image: {{ .Values.workflow_task_image }}
        command: [sh]
        source: |
          set -e
          curl https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/ghcnd-stations.txt > ghcnd-stations.csv
          cat ghcnd-stations.csv | wc -l
