apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: curl-ghcnd-stations-template
spec:
  serviceAccountName: operate-workflow-sa
  templates:
    - name: curl-ghcnd-stations
      script:
        image: {{ .Values.workflow_task_image }}
        command: [sh]
        source: |
          set -e
          curl https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/ghcnd-stations.txt > ghcnd-stations.csv
          cat ghcnd-stations.csv
    - name: curl-ghcnd-values
      inputs:
        parameters:
        -  name: station
      script:
        image: {{ .Values.workflow_task_image }}
        command: [sh]
        source: |
          set -e
          curl https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/all/{{`{{inputs.parameters.station}}`}}.dly > /{{`{{inputs.parameters.station}}`}}.dly
          cat /{{`{{inputs.parameters.station}}`}}.dly
