replicaCount: 1

image:
  repository: ghcr.io/linuxserver/openssh-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 22

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ssh:
  secretName: ssh-public-keys
  user: "jumpuser"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
  hosts:
    - host: jump.fugue-state.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: ssh-jumpbox-tls
      hosts:
        - jump.fugue-state.io