config:
  outputs: |
    [OUTPUT]
        Name s3
        Match *
        bucket fugue-state-backend
        region nyc3
        endpoint https://nyc3.digitaloceanspaces.com
        force_path_style On
        use_put_object On
        total_file_size 5M
        upload_timeout 10m
        store_dir /buffers
        s3_key_format /logs/$TAG/%Y/%m/%d/%H/%M/%S
        tls On
        compression gzip
        retry_limit False
  service: |
    [SERVICE]
        flush        1
        daemon       off
        log_level    info
        parsers_file parsers.conf

  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Tag kube.*
        Parser docker
        DB /var/log/flb_kube.db
        Mem_Buf_Limit 10MB
        Skip_Long_Lines On

  filters: ""   # <--- THIS removes default filters
  parsers: ""   # <--- Optional: if you're not using built-in ones

extraVolumeMounts:
  - name: buffers
    mountPath: /buffers

extraVolumes:
  - name: buffers
    emptyDir: {}
env:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: fluent-bit-s3-credentials
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: fluent-bit-s3-credentials
        key: AWS_SECRET_ACCESS_KEY
