kind: DaemonSet

rbac:
  create: true

service:
  type: ClusterIP
  port: 2020

input:
  enabled: true
  name: tail
  tag: kube.*
  path: /var/log/containers/*.log
  parser: docker
  refresh_interval: 10
  read_from_head: true

filters:
  enabled: true
  customParsers: |
    [FILTER]
        Name    kubernetes
        Match   kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

output:
  enabled: true
  name: loki
  match: "*"
  host: loki.default.svc.cluster.local
  port: 3100
  tls: off

volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers

volumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true

resources:
  limits:
    memory: 200Mi
    cpu: 200m
  requests:
    memory: 100Mi
    cpu: 100m
