loki:
  enabled: true

  # storage:
  #   type: s3
  #   s3:
  #     bucketnames: fugue-state-backend
  #     region: nyc3
  #     endpoint: https://nyc3.digitaloceanspaces.com
  #     s3forcepathstyle: true
  #     insecure: false
  persistence:
    enabled: true
    size: 10Gi
    accessModes:
      - ReadWriteOnce

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push

grafana:
  enabled: true
  adminPassword: "admin"
  service:
    type: ClusterIP
