loki:
  enabled: true

  persistence:
    enabled: true
    size: 10Gi
    accessModes:
      - ReadWriteOnce

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki-stack.loki-stack.svc.cluster.local:3100/loki/api/v1/push

grafana:
  enabled: true
  adminPassword: "admin"
  service:
    type: ClusterIP
  limits_config:
    ingestion_rate_mb: 10
    ingestion_burst_size_mb: 20
    max_age: 336h # allows logs up to 14 days old