apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  destination:
    namespace: velero
    server: "https://kubernetes.default.svc"
  project: fugue-state
  source:
    path: velero
    repoURL: "https://github.com/fugue-state-io/helm-charts"
    targetRevision: develop
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
