apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argo-cd.argoproj.io
spec:
  destination:
    namespace: argo-events
    server: "https://kubernetes.default.svc"
  project: fugue-state
  source:
    path: argo-events
    repoURL: 'https://github.com/fugue-state-io/helm-charts'
    targetRevision: develop