apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  destination:
    namespace: argo-events
    server: "https://kubernetes.default.svc"
  project: fugue-state
  sources:
  - repoURL: 'https://argoproj.github.io/argo-helm'
    chart: argo-events
    targetRevision:  2.4.1
    helm:
      valueFiles:
      - $values/argo-events/values.yaml
  - repoURL: 'https://github.com/fugue-state-io/helm-charts'
    ref: values
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true