apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  destination:
    namespace: argo-workflows
    server: "https://kubernetes.default.svc"
  project: fugue-state
  sources:
  - repoURL: 'https://argoproj.github.io/argo-helm'
    chart: argo-workflows
    targetRevision:  0.39.3
    helm:
      valueFiles:
      - $values/charts/argo-workflows/values.yaml
  - repoURL: 'https://github.com/fugue-state-io/helm-charts'
    ref: values
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true