apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-issuer
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  project: fugue-state
  source:
    path: cert-issuer
    repoURL: 'https://github.com/fugue-state-io/helm-charts'
    targetRevision: develop
  syncPolicy:
    automated:
      prune: false
      selfHeal: false