
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  project: fugue-state
  source:
    chart: cert-manager
    repoURL: 'https://charts.jetstack.io"'
    targetRevision: 1.1.23
    helm:
      parameters:
      - name: "installCRDs"
        value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: false