apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci
  namespace: argocd
spec:
  destination:
    namespace: ci
    server: "https://kubernetes.default.svc"
  project: fugue-state
  source:
    path: ci
    repoURL: 'https://github.com/fugue-state-io/helm-charts'
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: false