apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list:  etl=registry.digitalocean.com/fugue-state-registry/etl
    argocd-image-updater.argoproj.io/etl.helm.image-name: etl_image
    argocd-image-updater.argoproj.io/etl.helm.image-tag: etl_tag
    argocd-image-updater.argoproj.io/etl.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/etl.force-update: "true"
  name: ci
  namespace: argocd
spec:
  destination:
    namespace: ci
    server: "https://kubernetes.default.svc"
  project: fugue-state
  source:
    path: ci
    repoURL: 'https://github.com/fugue-state-io/helm-charts'
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true