apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  destination:
    namespace: fluent-bit
    server: "https://kubernetes.default.svc"
  project: fugue-state
  sources:
  - repoURL: 'https://fluent.github.io/helm-charts'
    chart: fluent-bit
    targetRevision: 1.17.1
    helm:
      valueFiles:
      - $values/fluent-bit/values.yaml
  - repoURL: 'https://github.com/fugue-state-io/helm-charts'
    ref: values
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true