apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fugue-state
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: fugue-state
    server: "https://kubernetes.default.svc"
  project: fugue-state
  source:
    path: fugue-state
    repoURL: 'https://github.com/fugue-state-io/helm-charts'
    targetRevision: develop