apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: ui=registry.digitalocean.com/fugue-state-registry/fugue-state-ui
    argocd-image-updater.argoproj.io/ui.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/ui.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/ui.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/ui.force-update: "true"
  name: fugue-state-ui
  namespace: argocd
spec:
  destination:
    namespace: ui
    server: "https://kubernetes.default.svc"
  project: fugue-state
  source:
    helm:
      passCredentials: false
    path: fugue-state-ui
    repoURL: "https://github.com/fugue-state-io/helm-charts"
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
