apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: api=registry.digitalocean.com/fugue-state-registry/fugue-state-api
    argocd-image-updater.argoproj.io/api.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/api.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/api.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/api.force-update: "true"
  name: fugue-state-api
  namespace: argocd
spec:
  destination:
    namespace: api
    server: "https://kubernetes.default.svc"
  project: fugue-state
  source:
    path: fugue-state-api
    repoURL: 'https://github.com/fugue-state-io/helm-charts'
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true