apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: keycloak
    server: "https://kubernetes.default.svc"
  project: fugue-state
  source:
    path: keycloak
    repoURL: 'https://github.com/fugue-state-io/helm-charts'
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true