apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  destination:
    namespace: loki-stack
    server: "https://kubernetes.default.svc"
  project: fugue-state
  sources:
    - repoURL: 'https://grafana.github.io/helm-charts'
      chart: loki-stack
      targetRevision: 2.10.2
      helm:
        valueFiles:
          - $values/loki-stack/values.yaml
      valuesFrom:
        - secretRef:
            name: grafana-admin-password
      parameters:
        - name: grafana.adminPassword
          value: '{{ admin-password }}'
    - repoURL: 'https://github.com/fugue-state-io/helm-charts'
      ref: values
      targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
