apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  destination:
    namespace: minio
    server: "https://kubernetes.default.svc"
  project: fugue-state
  source:
    path: minio
    repoURL: 'https://github.com/fugue-state-io/helm-charts'
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true