apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: processing
  namespace: argocd
spec:
  destination:
    namespace: processing
    server: "https://kubernetes.default.svc"
  project: fugue-state
  sources:
  - repoURL: 'https://github.com/fugue-state-io/helm-charts'
    path: processing
    targetRevision: develop
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true