apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  destination:
    namespace: reloader
    server: "https://kubernetes.default.svc"
  project: fugue-state
  sources:
  - repoURL: 'https://stakater.github.io/stakater-charts'
    chart: reloader
    targetRevision: 1.0.52
    helm:
      valueFiles:
      - $values/reloader/values.yaml
  - repoURL: 'https://github.com/fugue-state-io/helm-charts'
    ref: values
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true