
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: reloader
    server: "https://kubernetes.default.svc"
  project: fugue-state
  source:
    chart: reloader
    repoURL: 'https://stakater.github.io/stakater-charts"'
    targetRevision: 1.0.29
  syncPolicy:
    automated:
      prune: true
      selfHeal: false