apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zudell-io
  namespace: argocd
spec:
  destination:
    namespace: zudell-io
    server: "https://kubernetes.default.svc"
  project: zudell-io
  source:
    helm:
      passCredentials: false
    path: zudell-io
    repoURL: "https://github.com/fugue-state-io/helm-charts"
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
