auth:
  enabled: true
  existingSecret: redis-auth
  existingSecretPasswordKey: redis-password

architecture: standalone

master:
  persistence:
    enabled: true
    size: 1Gi
    storageClass: "standard" # Adjust based on your cluster's available classes

replica:
  replicaCount: 0

service:
  type: ClusterIP
